[package]
name = "TFTBot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
num-traits = "0.2"
env_logger = "0.10.0"
log = "0.4.0"

[env]
RUST_LOG="info"
RUST_BACKTRACE=1